// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type UmpireScorecard struct {
	ID               int64
	HomeTeam         interface{}
	AwayTeam         interface{}
	MaxRunsPerInning sql.NullInt64
	CreatedOn        int64
}

type UmpireScorecardInning struct {
	ID           int64
	ScorecardID  int64
	InningNumber int64
	IsHome       int64
	RunsScored   int64
	OutsRecorded int64
	CreatedOn    int64
}
